# Site settings
title: Inception | Code | Existence
header-img: img/home-bg.png
email: sushi@pathworks.co
copyright_name: schanrai
description: > # this means to ignore newlines until "baseurl:"
  Inception | Code | Existence
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Tominagirl
github_username:  schanrai
learn_profile: schanrai
email_username: sushi@pathworks.co

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
